server:
  port: 1991

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/assessment?serverTimezone=Asia/Shanghai@useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 270657
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  web:
    resources:
      static-locations: classpath:static/,file:static/
mybatis-plus:
  type-aliases-package: com.personalBlog.entity
  configuration:
    call-setters-on-nulls: false
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    field-strategy: 0
    banner: true
    db-config:
      id-type: uuid
      logic-not-delete-value: 1
      logic-delete-value: 0
logging:
  level:
    root: info
